### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by avcial** [entria/react-native-fontawesome#56] opened 2019-01-29 13:07 UTC
Try this now,

- init new react-native project --> react-native init FaExample

- see that project is running properly --> react-native run-android

- close bundle screen (cmd) and delete app on your device

 start to follow instructions on readme.md :

- add npm --> npm i --save react-native-fontawesome

- create mentioned directory on root of project, you will see  --> FaExample/assets/fonts 

![image](https://user-images.githubusercontent.com/28141784/51910237-b1d95400-23df-11e9-9181-20ef637aa428.png)

- add "rnpm" command to your package.json --> 

![image](https://user-images.githubusercontent.com/28141784/51910221-a84fec00-23df-11e9-9382-336c6cb74a65.png)

- download fontawesome files from link in readme.md

- open rar and navigate to "webfonts" file

- copy files "fa-brands-400.ttf, fa-regular-400.ttf, fa-solid-900.ttf" to FaExample/assets/fonts as mentioned

- run link command and see purple output lines--> react-native link

- copy first sample code from readme.md and paste in App.js --->  

```
import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View } from 'react-native';
import FontAwesome, { Icons } from 'react-native-fontawesome';

const instructions = Platform.select({
  ios: 'Press Cmd+R to reload,\n' + 'Cmd+D or shake for dev menu',
  android:
    'Double tap R on your keyboard to reload,\n' +
    'Shake or press menu button for dev menu',
});

type Props = {};
export default class App extends Component<Props> {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Welcome to React Native!</Text>
        <Text style={styles.instructions}>To get started, edit App.js</Text>
        <Text style={styles.instructions}>{instructions}</Text>
        <Text style={{ margin: 10, fontSize: 15, textAlign: 'left' }}>
          <FontAwesome>{Icons.chevronLeft}</FontAwesome>
          Text
      </Text>

      </View>
    );
  }
}

```

- run app again --> react-native run-android

so you will see the most amazing icon, crossed box,

![image](https://user-images.githubusercontent.com/28141784/51910081-34154880-23df-11e9-8750-873db481e253.png)

isn't it beautiful

so what is this?
what we made wrong? 
or you know,  What is wrong with  YOUR CODE?

**Comment by leandrosimoes** [comment] 2019-01-31 13:44
I really can't believe that a person who has two, maybe three contributions on GitHub can be such a d..., talking ironically like that? Really, what's the problem with these people?! 
Fist of all, you didn't follow the instructions because if you had followed it you would see that you have to use the `IconTypes` enum together with the `FontAwesome` component like this: 

`<FontAwesome type={IconTypes.FAR}>{Icons.chevronLeft}</FontAwesome>`

Another info to you, best programmer ever, is that there is already a PR open to fix the font files name used in the IconTypes, so if you are so bad a... , why you didn't see that before start to saying sh...? 
And when you said **YOUR CODE**, you're wrong about it, **AGAIN!**. This is a public repository, so this code belongs to the community, so why you don't fix it and open a new PR instead just complain about it, huh? You piece of s...

**Comment by avcial** [comment] 2019-01-31 14:12
You didn't even find the problem not even tolking about solution.
But i will f.. ( fix) your code.
Don't worry

**Comment by leandrosimoes** [comment] 2019-01-31 14:17
Oh yeah! But first you have to learn how to follow some instructions, otherwise open a PR will not that easy for you! haha

**Comment by leandrosimoes** [comment] 2019-01-31 14:22
I was curious about your experience, and I got a look at your GitHub profile and guess what?! All your GitHub are issues that you open and somebody close because you don't know how to follow instructions. How funny is that? hahahaha

**Comment by leandrosimoes** [comment] 2019-02-04 16:55
Closing because is not a code problem. The problem is just because the user don't know how to setup the project, even following the README instructions.

**Closed by leandrosimoes** 2019-02-04 16:55 UTC

**Comment by mslabenyak** [comment] 2019-03-06 12:51
You need to rename font files names, changing '-' with '_', ex. fa-regular-400.ttf -> fa_regular_400.ttf. And relink.

**Comment by jan-happy** [comment] 2019-03-20 10:36
@mslabenyak Thank you! That fixed the Android version for me!
